### ISSUE TITLE
Link instructions how to use VS Code a Git editor

### ISSUE THREAD

**Issue by bersbersbers** [joshbolduc/vscode-commitlint#294]
Maybe I should have done that ages ago, but I only recently made VS Code my git editor. I had to explicitly search for that, however, so maybe you want to link to https://code.visualstudio.com/docs/editor/versioncontrol#_vs-code-as-git-editor in the instructions.

On a related note, I still wonder if/how I can apply `commitlint` to commit messages authored in the GUI, and/or redirect to the text editor when the GUI commit message is empty:
![image](https://user-images.githubusercontent.com/12128514/141673115-1cc634c6-560e-4192-ae34-384f89d56091.png)

**Comment by joshbolduc** [comment]
Thanks for the feedback!

> Maybe I should have done that ages ago, but I only recently made VS Code my git editor. I had to explicitly search for that, however, so maybe you want to link to https://code.visualstudio.com/docs/editor/versioncontrol#_vs-code-as-git-editor in the instructions.

There are actually two links in the README to that very URL--one is in the description near the top ("A VS Code extension that integrates commitlint into **VS Code's commit editor**") and another at the bottom in the "Requirements" section ("VS Code as Git editor"). Of course, just because they are there does not mean they can't be too subtle to notice. Is there a way you think those instructions could be made more prominent in the README? Or were you thinking of exposing some instructions through the extension itself somehow?

> On a related note, I still wonder if/how I can apply `commitlint` to commit messages authored in the GUI, and/or redirect to the text editor when the GUI commit message is empty:

I'm not aware of any way to do this today, but there are at least a couple of related feature requests:

- https://github.com/microsoft/vscode/pull/95266 is a PR to redirect commits to the text editor.
- https://github.com/microsoft/vscode/issues/103128 is a backlog item to allow commands to be used in the small commit editor on the left side of your screenshot; I don't think it would bring diagnostics (i.e., red/yellow squiggly lines) to that editor, and it may not even work particularly well for real-time linting. But depending on how it were implemented, it might at least provide an avenue for some kind of linting feedback for commits written in that editor.

**Comment by bersbersbers** [comment]
> There are actually two links in the README to that very URL

You are totally right, and I feel appropriately stupid now ;) I find a small thing in my defense, which is that if I open that URL, this is what my screen looks like:

![image](https://user-images.githubusercontent.com/12128514/141697671-f9855701-c7b1-40c4-ba9a-8debd1046b53.png)

So the actual "VS Code as Git editor#" heading is hidden behind the cookie banner, and my eyes focused on the "diff tool" one which felt less relevant. I guess there's not a lot you can do if people miss that, but since you asked:

> ## Requirements
> To make the most out of this extension, you'll probably want to configure commitlint in your project and use VS Code as your git commit editor

I feel the "Requirements" section might be moved further up in the readme, and you could formulate this sentence in a way that makes it sound less optional :) "you'll probably want to" sounds like I can, but don't have to (while it is a hard requirement, unless I am mistaken) - especially when mentioned after a rather soft requirement (which I think it is because I assume commitlint has a default configuration that will work out of the box).

> > On a related note, I still wonder if/how I can apply `commitlint` to commit messages authored in the GUI, and/or redirect to the text editor when the GUI commit message is empty:
> 
> I'm not aware of any way to do this today, but there are at least a couple of related feature requests:

Thanks, I am tracking these now.

**Comment by joshbolduc** [comment]
> On a related note, I still wonder if/how I can apply `commitlint` to commit messages authored in the GUI, and/or redirect to the text editor when the GUI commit message is empty:

For posterity, https://github.com/microsoft/vscode/pull/95266 has been released, which makes it easier to use a full editor to write commits even without making VS Code the default commit editor.

Even better, TIL it's [actually possible to provide diagnostics for the SCM input box](https://github.com/microsoft/vscode/issues/35571#issuecomment-1184649829) after all:

![image](https://user-images.githubusercontent.com/25474557/179334658-066ee924-4c3b-41c4-9a73-521acd323f36.png)

I'll try to get a new release out that supports this soon.

**Comment by joshbolduc** [comment]
This is now implemented in [2.4.0](https://github.com/joshbolduc/vscode-commitlint/releases/tag/v2.4.0). I also reworked the README a bit to de-emphasize the need to set VS Code as your git commit editor, since it's no longer necessary.
