### ISSUE TITLE
seems not working

### ISSUE THREAD

**Issue by anb0s** [joshbolduc/vscode-commitlint#491]
I'm using commitlint with CI/CD and it works. After installing this plugin and configured code as commit editor it just does not show any message. How to debug?

Can it be related that in my workspace i have multiple projects?

**Comment by anb0s** [comment]
the file `.commitlintrc.json` is just:
```
{
  "extends": ["@commitlint/config-conventional"]
}
```

**Comment by anb0s** [comment]
![image](https://user-images.githubusercontent.com/95811/172471579-b53e9c7d-bae3-4be8-b65a-1bef98f2079e.png)

**Comment by joshbolduc** [comment]
Hmm, I tried replicating your config and couldn't reproduce the problem. I also tried putting it in a multi-root workspace and I still got linting errors.

Could you try enabling logging (set `commitlint.log.enabled` to `true`) and see what appears in the output panel under "commitlint" when you try to write a commit message?

**Comment by anb0s** [comment]
sorry i had another branch checked out, now the file is there:
```
{}
loading bundled version of @commitlint/lint as fallback
loading bundled version of @commitlint/parse as fallback
loading bundled version of @commitlint/load as fallback
Load config error stack:
Error: Cannot find module "@commitlint/config-conventional" from "/home/andre/git/plcapp"
loading bundled version of @commitlint/parse as fallback
loading bundled version of @commitlint/load as fallback
Load config error stack:
Error: Cannot find module "@commitlint/config-conventional" from "/home/andre/git/plcapp"
loading bundled version of @commitlint/parse as fallback
loading bundled version of @commitlint/parse as fallback
loading bundled version of @commitlint/load as fallback
loading bundled version of @commitlint/load as fallback
Load config error stack:
```

**Comment by joshbolduc** [comment]
Okay, interesting. For now at least, it should work if you install `@commitlint/config-conventional` as a local dependency.

I'll have to think about whether there's a good way to load globally installed libs in this case.

**Comment by joshbolduc** [comment]
This is a little tricky. It looks like commitlint has some issues with the exact configuration you seem to be using. If I try a similar setup to yours with the dependencies installed globally, the official CLI doesn't work for me. This seems to be known and somewhat environment-dependent: https://github.com/conventional-changelog/commitlint/issues/613

Since it does work for you, though, I've put together some changes that might help. If you'd like to give it a shot you can try manually installing the VSIX archived here and let me know if it works where the current version doesn't, without installing `@commitlint/config-conventional` locally in your project: https://github.com/joshbolduc/vscode-commitlint/actions/runs/2472240861

**Comment by anb0s** [comment]
thanks, i've installed the version from build (v2.2.0)

![image](https://user-images.githubusercontent.com/95811/173035761-a1ad8654-e6ee-41e0-9974-405335302774.png)

the issue is the same.
```
oad config error stack:
Error: Cannot find module "@commitlint/config-conventional" from "/home/andre/git/plcapp"
loading @commitlint/parse dynamically via /usr/local/lib/node_modules/@commitlint/cli/node_modules/@commitlint/parse/lib/index.js
loading @commitlint/load dynamically via /usr/local/lib/node_modules/@commitlint/cli/node_modules/@commitlint/load/lib/load.js
Load config error stack:
Error: Cannot find module "@commitlint/config-conventional" from "/home/andre/git/plcapp"
```

BTW: i'm using Linux at Windows (WLS2)

**Comment by anb0s** [comment]
I've installed now localy to verify if it works with WSL2 and it's working:
```
loading @commitlint/lint dynamically via /usr/local/lib/node_modules/@commitlint/cli/node_modules/@commitlint/lint/lib/lint.js
loading @commitlint/parse dynamically via /usr/local/lib/node_modules/@commitlint/cli/node_modules/@commitlint/parse/lib/index.js
loading @commitlint/load dynamically via /usr/local/lib/node_modules/@commitlint/cli/node_modules/@commitlint/load/lib/load.js
[6/10/2022, 11:32:16 AM] loadOptions: {"cwd":"/home/andre/git/plcapp/.git/COMMIT_EDITMSG"}
[6/10/2022, 11:32:16 AM] 11 commitlint rules:
{"body-leading-blank":[1,"always"],"body-max-line-length":[2,"always",100],"footer-leading-blank":[1,"always"],"footer-max-line-length":[2,"always",100],"header-max-length":[2,"always",100],"subject-case":[2,"never",["sentence-case","start-case","pascal-case","upper-case"]],"subject-empty":[2,"never"],"subject-full-stop":[2,"never","."],"type-case":[2,"always","lower-case"],"type-empty":[2,"never"],"type-enum":[2,"always",["build","chore","ci","docs","feat","fix","perf","refactor","revert","style","test"]]}
loading @commitlint/lint dynamically via /usr/local/lib/node_modules/@commitlint/cli/node_modules/@commitlint/lint/lib/lint.js
```

![image](https://user-images.githubusercontent.com/95811/173039297-f8cfe813-ee2f-4ec7-a320-c233075ef75b.png)

we wanted to avoid this, because the projects are not js/npm and we do not want to do it for each project and therefore only configured once globaly in dev environment and avoid this files to be created:
```
Untracked files:
  (use "git add <file>..." to include in what will be committed)
        node_modules/
        package-lock.json
        package.json
```

**Comment by joshbolduc** [comment]
Okay, I was able to put together an environment that reproduces the issue, and I think I have some understanding of what's going on now.

commitlint ultimately [`global-dirs`](https://www.npmjs.com/package/global-dirs) to help it resolve configurations referenced by `extends`. That library, in turn, determines where to find globally installed packages [based on the `execPath` (among other things)](https://github.com/sindresorhus/global-dirs/blob/7882d048d6223b1b6c9d509e6ebd07617a36a6dd/index.js#L48). In the context of this extension, though, the `execPath` will map to a bundled VSCode executable, not your globally installed copy of `node`. So it won't actually resolve your globally installed copy of `@commitlint/config-conventional` because it's looking in the wrong place.

There's a way to override the global path with an env var, which I was able to use to fix the problem in a limited test. It feels kind of sketchy, but I'm not sure I can see a better approach. I'll have to do some more testing.

**Comment by joshbolduc** [comment]
I have another test build here if you'd like to try it: https://github.com/joshbolduc/vscode-commitlint/suites/6932577337/artifacts/269853807

The fix is kind of clunky, but in my testing it seemed to work.

**Comment by anb0s** [comment]
Thanks 👍 

It works now without local installation:

![image](https://user-images.githubusercontent.com/95811/173841738-5d7411c8-9f77-435c-9139-c7495e407430.png)

It would be cool to have this version officially release :)

**Comment by joshbolduc** [comment]
> It would be cool to have this version officially released :)

Agreed! [2.3.0](https://github.com/joshbolduc/vscode-commitlint/releases/tag/v2.3.0) has now been released with the fix.

Thanks for your help in tracking down the problem and verifying that the fix works!

**Comment by anb0s** [comment]
Greate 👍 

Your are welcome and thank you for the plugin!

Just verified the 2.3.0 and it works, forwarding this to my coworkers 😄

**Comment by thymbahutymba** [comment]
Facing the same issue using version 2.6.2. It works if I link the node_modules directory to my project root. I'm using WSL2. Any clue how to fix it again?
