### ISSUE TITLE
Can it prompt for the common files?

### ISSUE THREAD

**Issue by yi-Xu-0100** [joshbolduc/vscode-commitlint#69]
Could it prompt a formatted message for the files which type is `Git Commit Message`?

![image](https://user-images.githubusercontent.com/25523606/113497641-9c6c9100-9538-11eb-8430-cf609a81a9ae.png)

![image](https://user-images.githubusercontent.com/25523606/113497650-a55d6280-9538-11eb-89a2-7451e6819b7b.png)

This file is created by the extension - [vscode-conventional-commits](https://github.com/vivaxy/vscode-conventional-commits).
The file uses the `conventionalCommits.showEditor` option to open the commit message in a separate tab.
And the file seems not at the current workspace. Could it use the configuration of the current workspace?

**Comment by joshbolduc** [comment]
Thanks for the report. This is interesting.

It looks like that extension uses a custom filesystem provider for that editor, and the file's URI uses a custom scheme. Since we don't recognize the custom schema we treat it like a file on the filesystem and ask commitlint to load a configuration for that path (which it won't, because the path isn't really on the filesystem). There is already special case handling for untitled files; I think doing the same for non-`file` schemes would make sense anyway and address this issue.

Another option could just be to try to use a config for the workspace whenever we fail to load any valid rules, under the assumption that it's probably due to lack of a valid configuration. I don't think there's a way to tell whether a config was found from `@commitlint/load`, you just get the resulting configuration. I'm a little unsure whether this change would make sense, since even though I can't think of a good reason to have a configuration without any rules, it might be more confusing to impose a different set of rules instead.

Handling non-`file` schemes is a simple change. I'll push something up.
